name: Checks
on:
  push:
    branches:
    - master
    - spellchecking_test
  pull_request:

jobs:
  spellchecking:
    name: Spellchecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: rust-lang-ru/common-configs
        path: common-configs
    - name: Get all changed markdown files
      uses: tj-actions/changed-files@v45
      id: changed_files
      with:
        files: |
           ru/**.md
    - uses: funkill/spellcheck-github-actions@hunspell-support-action
      with:
        task_name: Markdown
        source_files: ${{ steps.changed_files.outputs.all_changed_files }}
  gitlocalize-bug-checking:
    name: Checking Gitlocalize bugs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rust-lang-ru/simpleinfra/gitocalize-bug-checker@master
