name: Checks
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Spellchecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10
    - uses: actions/checkout@v3
      with:
        repository: rust-lang-ru/common-configs
        path: common-configs
    - run: npm install yaspeller
    - run: git show -m --name-only -1 --diff-filter=ACMRT --format="format:" ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep --color=never -i '.md' | xargs node_modules/.bin/yaspeller -c common-configs/.yaspellerrc
  gitlocalize-bug-checking:
    name: Checking Gitlocalize bugs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rust-lang-ru/simpleinfra/gitocalize-bug-checker@master
